### ISSUE TITLE
Token Problem

### ISSUE THREAD

**Issue by mario4dev** [L480/tildas-tonies#1]
Hello, very good idea, so you can show your family and friends the Tonies you have, unfortunately it doesn't work properly for me.

"Get access token and save new refresh token to KV" don't work

If I insert refresh token and access token manually into the Javascript, no error messages appear during debugging and the KV is saved correctly. 
Otherwise it is saved as “undefined”.

Do you have an idea? Is this a settings issue with Cloudflare?

**Comment by L480** [comment]
You would need to deploy the worker, link the KV namespace, grab the refresh token manually from the Tonies website, add it to KV, and then access your page. Afterwards the latest refresh token should be stored in KV.

**Comment by mario4dev** [comment]
Yes, that's exactly how I did it.
Unfortunately, the last refresh token is not saved. The KV is then changed to "undefined"
Screenshot:
![image](https://github.com/user-attachments/assets/08b5e5ca-9957-4450-90b0-34956f6323dd)
![image](https://github.com/user-attachments/assets/bafdf15c-53b8-43df-b94d-a3cc7585c362)

**Comment by L480** [comment]
Did you get the token from https://my.tonies.com/content-tonies ?

**Comment by mario4dev** [comment]
> Did you get the token from https://my.tonies.com/content-tonies ?
Yes from this site.

**Comment by L480** [comment]
Can you share the login URL?

It should be `https://login.tonies.com/auth/realms/tonies/protocol/openid-connect/auth?client_id=my-tonies`... not `https://login.tonies.com/auth/realms/tonies/protocol/openid-connect/auth?client_id=shop-uk-frontend`...

**Comment by mario4dev** [comment]
On your Link (https://login.tonies.com/auth/realms/tonies/protocol/openid-connect/auth?client_id=my-tonies) i have a Error 400 
![image](https://github.com/user-attachments/assets/3758fff4-2f63-4b83-8eb5-9f9dcc8193c1)


When i go to tonies login i have this link:
https://login.tonies.com/auth/realms/tonies/protocol/openid-connect/auth?client_id=my-tonies&redirect_uri=https%3A%2F%2Fmy.tonies.com%2Flogin%3Fredirect%3D%252F&state=xxxx&response_mode=fragment&response_type=code&scope=openid&nonce=xxxx&ui_locales=de

xxxx= placeholder

the refresh token is from my.tonies.com, because in login.tonies.com i dont have in local storage a refresh token: 
![image](https://github.com/user-attachments/assets/7fd38f0c-22f3-40f7-ad32-45cff895770e)

**Comment by L480** [comment]
Can you try to grab the token directly from the response?
![image](https://github.com/user-attachments/assets/b13366fc-8858-4fd6-b705-448c7fa7a5f5)

**Comment by mario4dev** [comment]
Same problem with token from response
![image](https://github.com/user-attachments/assets/4706dceb-28c0-4e4d-b48c-416abae48d0f)

**Comment by mario4dev** [comment]
oh my fault... 

I have deactivated the browser cache at Cloudflare and now it works.
